// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ezimysduhaladzbghfnv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV6aW15c2R1aGFsYWR6YmdoZm52Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1ODIxNzMsImV4cCI6MjA2NDE1ODE3M30.mPxikYxzud70q6rcrtREtqaensymPDs8A_OwU81TuHc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);